### PR TITLE
Ghostery is crap! Closed source now, says everything

### PR DESCRIPTION
**Pull request by CHEF-KOCH**
- Removed Ghostery, we not want to support it ... no one needs this especially they working with ads industry together to sell the lists .... Nothing beets uBlock/uMatrix for sure! 
- Added #150

### CODE REVIEW

**Comment by Gitoffthelawn** [comment]
Thanks Chef-Koch.  Do you have some good links so we can read about it?  Do you know if this affects their Android browser app as well?  I took a look at their Android browser, and it appears to have a way to turn off their data collection.  I used to recommend it, but I don't use it myself, and am not sure if it is wise to recommend.

In order to trust any of these tools, you have to read all the source code and create the xpi's (or for Android apps, compile them) yourself.  Critical reviews of the Ghostery extension have reportedly been deleted, causing concerns.  But now critical reviews of uBlock Origin and Adblock Plus are also reportedly being deleted, causing similar concerns.

When I see critical reviews, I take a screenshot of them.  If I then go back and look at the reviews, most of the critical reviews have been deleted.  I've noticed this for uBlock Origin and Adblock Plus, and others have reported it for Ghostery.  It's quite suspicious.

On top of those reported issues, the uBlock Origin developer blocked me from that repo.  He never told me why, but I'm guessing it was because I was being helpful by improving the wiki (which was in bad shape).  Part of that process was being more honest and accurate about comparisons to other tools (his tests were very biased).  When I made the wiki more honest and accurate, the uBlock Origin developer blocked me from the repo.  That's not in the spirit of open-source software at all.

**Comment by CHEF-KOCH** [comment]
[Ghostery EULA](https://www.ghostery.com/about-us/privacy-statements/ghostery-product/ghostery-product-eula/) - This year changed! It affects every of their Products, if you search their page you also see Terms like 'sell' or 'for Industry' and such. uBlock works on Android too btw. 

I may contact the uBlock dev and ask him about you. I think uBlock never censorship anyone, maybe it was/is a mistake or other reasons, because I see a lot of people reporting useless things which is waste of time and remember he not gets or want any money!

I also got blocked sometimes, but's more (speaking about Wiki) GitHub issue, sometimes if you commit something it 'reverts' somehow your privileges, but i will ask him - for sure I promise.

**Comment by Gitoffthelawn** [comment]
@CHEF-KOCH Thanks Chef-Koch.  I don't have time right now (or, honestly, the interest), but take a look at the uBlock Origin wiki and see if he reverted my edits where I made his comparisons to other tools more honest and accurate.  I can't remember if he reverted things, but I seem to recall that he did.  If so, that reflects poorly on the uBlock Origin project and its openness.  I have no bias, I simply desire the best tools and for everyone to be honest.

Note that other people have also reported being blocked by the uBlock Origin developer, so there seems to be a pattern of behavior.  It's unlikely to be a GitHub issue.

Back to Ghostery... Ghostery discloses that they include an opt-in option to sell data to industry.  I would prefer they didn't have that option, but they are a for-profit organization, so they want a way to make money on their products.

Is it weird and unsettling that a privacy tool has an option to sell data?  Absolutely.

But since they disclose it and they claim it is opt-in (versus opt-out), I think it's not a deal-breaker for many people.  Note that I have not verified the opt-in nature of this.

I did just temporarily install the Ghostery Android app for a moment to see how that looks.  Here's what I found:

- There was a GhostRank option with a simple toggle.  The option was easy to access and was not hidden or obscured in any way.
- There was an *In-App Privacy* setting.  The setting was easy to access and was not hidden or obscured in any way.
 - When I clicked on the *In-App Privacy* setting, it displayed a page that said: *"Our company, with help from our partners, collects data about your use of this app.  We respect your privacy and if you would like to limit the data we collect please use..."*.
 - The above text was then immediately followed by a label entitled *Opt In (To all trackers listed below)*, followed by *None* and *All* radio buttons.  It was a little disconcerting that I could ***not*** select either button, making it ambiguous what was happening.
 - Under the radio buttons, there was the text *"The list of trackers could not be loaded.  Please ensure you have internet access, and try again later."*.  I didn't have time to investigate it, but I think I was probably blocking something that prevented them from loading the list of trackers.
 - ***Important:*** In this case, I think it would have been better if they made it clear whether or not any trackers were in effect... I don't think so, but I'm not completely sure by the information they presented.

Note that I did not have time to inspect all the packets being transmitted/received in order to verify any claims.

In my opinion, I don't like a privacy app having the option to collect data.  It seems bizarre and could *potentially* lead to a conflict of interest.  But given that they seem to make it easy to opt-out of all data collection, and they claim everything is opt-in (again, I did not verify this), I don't think it will be a deal-breaker for many people.

The fact that critical reviews of their browser extension have reportedly been deleted is a **red flag**, however.  Critical reviews of uBlock Origin and Adblock Plus have *definitely* been deleted, which is a big **red flag** for those products as well.

Overall, when I review the data, I see sufficient evidence to cause me to be concerned about trusting any of these three products (Ghostery, uBlock Origin, Adblock Plus).  I don't, however, see sufficient data to single out Ghostery as a problem.

**Comment by CHEF-KOCH** [comment]
Well this is the last stuff I say ever about Ghostery here, because it's annoys me (not because the talk itself) more because I never got any real answer from them.

I think user.js and other public projects on GitHub should (if possible) suggest/recommend 'trusted' and transparent solutions. It's more because philosophy/ethical reasons not only because they may want to play it to get money - it would be okay as long we would have a minimum on control. I not say opening the source is sometimes better because I do agree they just could pickup the free list over GitHub like Disconnect, Easylist and others but the difference here is, everyone can/could see it and the original author not get paid for such behavior. I only recommend or suggest stuff which I tested myself and which works (if possible) on all systems otherwise I mention it, I think user.js already mention it too that it's up to everyone to use it or not, but again ethical/moralic? Why we not use solutions which are directly usable/open and known as 'trusted'? Of course like everyone else I not have time to compile all of my over 1k starred projects myself, so this is why I simply must trust and verify it - Ghostery mad the decision to not work with people together, I tried it, their FAQ was reduced to only 3 points and the important points was more or less integrated into the EULA which also not allows to fork it, even if we would get any source. 

Another ethical reason is that since you can't look behind you don't know if there are not made exceptions for their partners which may paid for this. Unpacking the addon not anymore helps because you not see the server side connections and what it really downloads as 'filter update' you only see the server which stores their lists. 

I don't know what you want exactly try here, maybe because of possible censorship you try to push Ghostery but remember that as a developer it's your right to contact the page which wrote the review and 'correct' the article it it may was wrong or fixed in the meantime. I think it's not censorship, censorship would be to more to remove the entire article (if that is really true) or in your example that you not get any access to the project without any 'reasons'.

The thing is that I take such thing seriously because I think if we are here public we have a responsibility to others if we suggest/recommend something. I myself never trusted AdBlock or Ghostery much because it was/is known they sell data but the thing about is as said, it's intransparent. In AdGuard/uBlock you have the control not them because you see what filter lists, the source (it's mostly mentioned if you download the list open the editors and see last changes, authors and and and) + the ethical aspect - don't forgot that uBlock never said like Ghostery 'take control of your digital experience' they never claimed it blocks 'everything' I think there is a huge difference in the web presents and the history.

Btw I checked today Wikipedia again, seems it was [restored](https://en.wikipedia.org/wiki/Ghostery#Criticism). But just in case I made a screenshot. 

ghostery


What are my last words on this now?
* I tried to contact and get the source from ghostery (my story is written down here on github)
* I will try to contact the uBlock developer to reveal the truth and ask him why several peoples are blocked - I still think that there exist reasons, it's not what I know from gorhill. Normally he is friendly. 
* I will not recommend Ghostery if we have alternatives, which btw working same good on Thunderbird or Android FF.
* Ethical/moralic reasons.
* The time I spent on such discussions is pretty much useless, not because the talk itself, more because I know maybe someone other come with other addons and try the same - maybe to push or make other extensions less good.
* New is not better but uBlock exist now for several years. I think if there was security issue someone had already notice it, the fact that it's an non profit addon should be preferred over solutions which are intransparent. 
* If possible we should general use as less addons/extensions as possible but I think everyone know that already.
* If there are any other issue, everyone can contact me via email. 

CK

**Comment by DrunkenSasquatch** [comment]
@CHEF-KOCH 
>Closed source now

Correct me if I'm wrong, but aren't all XPI packages inherently open source? You can just open the XPI and inspect the code yourself. I think you mean that there is no public repository - that doesn't mean Ghostery is "closed source".

@Gitoffthelawn 
>the uBlock Origin developer actually blocked me from that repo

Interesting, I've noticed you have a pending bug issue which I have responded to [here](https://github.com/gorhill/uBlock/issues/1977). 

Small world huh? :smile:

**Comment by pyllyukko** [comment]
Ghostery stays on the list for now at least.

**Pull request closed without merging**
