### PR TITLE
added update hardening

### PR DESCRIPTION
**Pull request by CHEF-KOCH**
Biggest weakness I can see it still the about:config update change problem in FF so we ensure we use all the latest url's. Of course if you decided to no use e.g. peerconnection it makes less sense but not everyone disabled it so give them the ability to use the latest secured servers and update resources.

### CODE REVIEW

**Comment by fmarier** [comment]
I don't get why you're explicitly setting these URLs to the defaults. If you don't customize a pref and leave it to be the default, Firefox will update it automatically if it changes in the future.

**Comment by CHEF-KOCH** [comment]
No, not from my experience, FF never ovverides on updates (dirty install over existent installation) such kind of url's. I tried it, e.g. use FF 39 and start it, close it and upgrade to a newer one and you will see it still uses the old servers.

**Comment by fmarier** [comment]
> No, not from my experience, FF never overrides on updates (dirty install over existent installation) such kind of url's. I tried it, e.g. use FF 39 and start it, close it and upgrade to a newer one and you will see it still uses the old servers.

If you can reproduce this, please file a bug against Firefox. It would be a fairly important bug.

**Comment by CHEF-KOCH** [comment]
I can reproduce this, but as I said over another thread I lost my entire BugZilla account. I think the entire about:config must be re-written because there are several more 'problems/bugs' or 'by design' thins that are really annoying, it start's with the fact that there is no API to detect and automatically revert changes (must use an new profile). Most plugins reverting this with an additional .js which compares current settings with there provided one. :-1:

**Comment by nodiscc** [comment]
I can't reproduce this on Iceweasel 41.0.2-1

**Comment by CHEF-KOCH** [comment]
Did you create another profile for test? Because in such a case Mozilla always starts with defaults (and of course with the new version with it's new defaults). Mozilla changed that now long time ago, try to upgrade form an older version and you will see.

* Eg use FF 33 
* Download and dirty install FF 41 over it 
* Now you will see

**Comment by fmarier** [comment]
Download [Firefox 38](https://www.mozilla.org/en-US/firefox/organizations/all/) and create a new profile:

    ./firefox --no-remote -P

Then open `about:config` and notice this:

    browser.trackingprotection.gethashURL = "https://tracking.services.mozilla.com/gethash?client=SAFEBROWSING_ID&appver=%VERSION%&pver=2.2"

Close Firefox.

Now download [Firefox 42](https://www.mozilla.org/en-US/firefox/beta/all/) and open the same profile.

Look at the same pref in `about:config`:

    browser.trackingprotection.gethashURL = https://shavar.services.mozilla.com/gethash?client=SAFEBROWSING_ID&appver=%VERSION%&pver=2.2

The URL was automatically updated in the profile **because** it hadn't been customized. So merging this PR will actually prevent Firefox from keeping URLs up to date.

**Comment by CHEF-KOCH** [comment]
Huh, I use shavar.services.mozilla.com in my commit.

But in this case we still have the issue that such important parts not getting updated so how to handle?

**Comment by nodiscc** [comment]
Such parts _do_get updated _if_ you left the default value intact. The solution is to not alter these values at all.

**Comment by pyllyukko** [comment]
I guess that settles it.

**Comment by CHEF-KOCH** [comment]
I can't confirm with FF 33 and default settings, but okay. Maybe this was/is an internal bug but I still think that this is useful anyway to stay on the line because if someone uses an older version he also want's to get the latest update resources. So and if he not upgrades or created an new profile he will suffer from this. 

So this is for me not understandable to nor merge it. But okay.

**Comment by pyllyukko** [comment]
There's already plenty of work trying to keep up with all the settings and features, so I think in that sense also, it's best to let FF handle these.

**Pull request closed without merging**
