### PR TITLE
Remove default website protocol handlers

### PR DESCRIPTION
**Pull request by CHEF-KOCH**
No one (and I'm sure ever) use this, gmail is comment out because it could be useful if you use webmail but the other services are not widley used or there are better extension for it

### CODE REVIEW

**Comment by pyllyukko** [comment]
Do these settings matter at all?

**Comment by Gitoffthelawn** [comment]
I think some people use Mibbit for IRC.

**Comment by CHEF-KOCH** [comment]
On external addons you can simply implement your own protocol handler to add e.g. irc, so I see no problem there is also an Mozilla page which explains how to add protocol handlers to your extension/addon.

**Comment by nodiscc** [comment]
I have other prefs in place for this:

```js
user.js:user_pref("network.protocol-handler.app.irc", "/usr/bin/transmission-gtk");
user.js:user_pref("network.protocol-handler.app.magnet", "/usr/bin/transmission-gtk");
user.js:user_pref("network.protocol-handler.expose.sftp", false);
user.js:user_pref("network.protocol-handler.external.irc", true);
user.js:user_pref("network.protocol-handler.external.magnet", true);

```

Whereas you use `gecko.handlerService.schemes.*`. Which one is correct?

Also I think this falls into the "Personal user preferences" category and could be discarded.

**Pull request closed without merging**
