### PR TITLE
remove "What does it do?" settings listing:

### PR DESCRIPTION
**Pull request by nodiscc**
Outdated, see below.

### CODE REVIEW

**Comment by nodiscc** [comment]
The last commit https://github.com/pyllyukko/user.js/pull/229/commits/d312f513bb08511c8713e2ff93db3da8d1791976 removes 2 preferences that I think are unneeded/incorreclty described/need more research.

**Comment by nodiscc** [comment]
I have started working on a mechanism to generate an index of changed preferences, in markdown format. When completed it can be used to generate the README's "what does it do section" formatted as

 * HTML5/DOM APIs: Disable HTML5/DOM media/p2p/geo/sensors/... APIs [[?](https://github.com/nodiscc/user.js/blob/wiki-migration/user.js#L7)]
   * Disable Service Workers [[?](https://github.com/nodiscc/user.js/blob/wiki-migration/user.js#L12)]
   * Disable notifications [[?](https://github.com/nodiscc/user.js/blob/wiki-migration/user.js#20)]
   * Make sure the User Timing API does not provide a new high resolution timestamp [[?](https://github.com/nodiscc/user.js/blob/wiki-migration/user.js#24)]
   * ...
 * Misc: Settings that do not belong to other sections or are user specific prefs [[?](https://github.com/nodiscc/user.js/blob/wiki-migration/user.js#L153)]
 * ...

In the current state, `make` output is the following:

```
7: * SECTION: HTML5/DOM APIs
12:// PREF: Disable Service Workers
20:// PREF: Disable notifications
24:// PREF: Make sure the User Timing API does not provide a new high resolution timestamp
28:// PREF: Disable Web Audio API
32:// PREF: Disable Location-Aware Browsing (geolocation)
36:// PREF: Disable dom.mozTCPSocket.enabled (raw TCP socket support)
42:// PREF: Disable DOM storage (disabled)
48:// PREF: Whether JS can get information about the network/browser connection
55:// PREF: Disable WebRTC entirely
64:// PREF: Disable WebRTC getUserMedia, screen sharing, audio capture, video capture
73:// PREF: Disable battery API
77:// PREF: Disable telephony API
81:// PREF: Disable DOM timing API
85:// PREF: Disable "beacon" asynchronous HTTP transfers (used for analytics)
89:// PREF: Disable clipboard manipulation via JavaScript
93:// PREF: Disable speech recognition
99:// PREF: Disable speech synthesis
103:// PREF: Disable sensor API
107:// PREF: Disable pinging URIs specified in HTML <a> ping= attributes
111:// PREF: When browser pings are enabled, only allow pinging the same host as the origin page
115:// PREF: ??
125:// PREF: Disable gamepad input
129:// PREF: Disable virtual reality devices
133:// PREF: Disable webGL
137:// PREF: When webGL is enabled, use the minimum capability mode
139:// PREF: ??
142:// PREF: ??
145:// PREF: ??
153: * SECTION: Misc
248: * SECTION: Extensions / plugins
292: * SECTION: Firefox (anti-)features / components
406: * SECTION: Automatic connections
459: * SECTION: HTTP
510: * SECTION: Caching
600: * SECTION: UI related
679: * SECTION: Cryptography (TLS / HTTPS / OCSP / HSTS / HPKP ...)
759: * SECTION: Ciphers

**Comment by pyllyukko** [comment]
I'm not entirely sure about all this. I mean I get the point that it would be nice to be able to just update one place where setting specific information is, but I'm not sure whether it's so easily resolved.

I also realize, that the "highlights" part needs some rework/review/update.

Also the README and the explanations profit from markdown syntax so we can do formatting, links etc., which we can't put into the .js file.

**Comment by nodiscc** [comment]
> d312f51: I think these should be handled in separate issue/PR

Moved to https://github.com/pyllyukko/user.js/pull/230, reverted here.

**Comment by nodiscc** [comment]
>  I get the point that it would be nice to be able to just update one place where setting specific information is
> "highlights" part needs some rework/review/update.
> README and the explanations profit from markdown syntax so we can do formatting, links etc

Yes that is the point of this PR. I figured the best course would be

1. Deduplicating links and moving them along respective prefs (https://github.com/pyllyukko/user.js/pull/229/commits/2c0c031e823425f3528a9c7bad684c811f1601bc)
2. Automatically generating markdown from information in the user.js file (last commit, incomplete work, see below)

@pyllyukko Regarding 2. could you please provide an example of a final, markdown formatted section you consider appropriate? (For example what should the final HTML5/DOM APIs section look like).

> which we can't put into the .js file.

Such info can be added to the section header/other comments/... would you agree? Or we can find a workaround. The point is, manual management of `"what does it do?"` is high-maintenance, error-prone, etc.

**Comment by nodiscc** [comment]
Makefile updated.
Current output can be seen at https://gist.github.com/nodiscc/43e75ab753efadb718302d91d9f37511
Let me know if you're ok with that method, and if it requires further changes.

**Comment by pyllyukko** [comment]
> @pyllyukko Regarding 2. could you please provide an example of a final, markdown formatted section you consider appropriate? (For example what should the final HTML5/DOM APIs section look like).

I think we should be able to generate (almost) similar than what it is now. For the most parts it could be possible, but for instance the longer paragraphs in the beginning of the sections could be static in the README. Maybe the related links could be after the description, e.g. ```* Disable Service Workers[1][2][3]```.

> Such info can be added to the section header/other comments/... would you agree? Or we can find a workaround.

In the README that is?

> The point is, manual management of "what does it do?" is high-maintenance, error-prone, etc.

That is absolutely true.

**Comment by nodiscc** [comment]
Rebased as 2 commits: https://github.com/pyllyukko/user.js/pull/229/commits

```
    Automate README 'What does it do' section generation, doc. improvements/organization
    
    * Doc improvements/reorganization:
      * user.js: improve/simplify preferences descriptions, move multiline descriptions to single line
      * reorganize: move all test suites to README, sort/group tests, reorder links, remove duplicates
    
    * Automate README 'What does it do' section generation:
      * README: remove hardcoded markdown "What does it do?" settings listing
        * move information to relevant user.js prefs/sections
      * user.js: add SECTION: prefix for section titles, add PREF: prefix for preferences
      * Add a basic makefile with a single target
      * Add a shell script 'gen-readme.sh' to generate 'What does it do' section:
        * For each section header in user.js, display a generaic description of the section
          Custom markdown text can be set for each section in 'gen-readme.sh' (config section)
          user.js: remove section descriptions, move to config options in gen-readme.sh
        * For each preference, append a list of reference links from user.js
        * Write the section to README.md, delimited by HTML tags BEGIN/END SECTION
    * Misc. removals:
      * Remove tshark/wireshark snippet: tshark -t ad -n -i wlan0 -T text -V -R ssl.handshake
      * remove "to use developer tools in the context of the browser itself, and not only web content"
    
    Part of #220

   * run 'make', update README 'what does it do' section from user.js
```

**Comment by nodiscc** [comment]
Added a commit: 1dc01e6

```
issue 208 item 401 (extensions.blocklist), improve OCSP docn enable OCSP must-staple

 * Add extensions.blocklist.url pref, Fixes item 0401 Sanitize blocklist url of #208
 * improve documentation on extensions.blocklist.enabled
 * add services.blocklist.update_enabled = true
 * improve documentation on OCSP
 * enable OCSP must-staple extension
 ```

**Comment by pyllyukko** [comment]
> Preview: https://github.com/nodiscc/user.js/blob/wiki-migration/README.md#what-does-it-do

I have to admit that it's starting to look good :)

**Comment by nodiscc** [comment]
@pyllyukko I think this could be merged in the current state. There are still prefs named `??` but filling in appropriate names can be done after this is merged. Just run `make` to auto-update the README.

**Comment by pyllyukko** [comment]
Ok. So everything regarding this is now implemented? I'll need to review this more thoroughly before merging. I'll refrain from pushing any more commits before addressing this.

I'm afraid we'll need one more rebase still :)

**Comment by nodiscc** [comment]
I've merged `master` (easier than rebasing). I'll wait for your review before working on other tasks. Thanks :)

**Comment by pyllyukko** [comment]
Should we ditch the commented out settings from the README? I see that you have just included a "(disabled)" suffix, but maybe we don't need to clutter the README with those.

**Comment by nodiscc** [comment]
I can exclude `(disabled)` items from being added from the README.

**Comment by pyllyukko** [comment]
I'm trying to merge this today, as I'm quite busy with other stuff for the rest of this week. You can see my changes so far in the [nodiscc-wiki-migration](https://github.com/pyllyukko/user.js/tree/nodiscc-wiki-migration) branch.

**Comment by pyllyukko** [comment]
> There are still prefs named ?? but filling in appropriate names can be done after this is merged.

I replaced all the "??" with at least the pref's name (6d92170b2f090056d155b8d0b06f719f1792cf40). We need to make a separate issue to fill in the blanks.

**Comment by pyllyukko** [comment]
Boom!

**Comment by pyllyukko** [comment]
I also created #236

**Comment by pyllyukko** [comment]
Huge thanks for the effort @nodiscc! Even though I was a bit sceptic in the beginning, this turned out to be a huge improvement regarding our documentation. I think it also helps us in the future because we need to write the description/reasoning for each pref and thus improving the overall quality of this project.

**Pull request merged**
