### PR TITLE
add various preferences to user.js/ignore.list:

### PR DESCRIPTION
**Pull request by nodiscc**
user.js:
 * fallback on mozilla wifi geolocation services when user re-enables geolocation (instead of Google services)
 * disable geolocation requests logging in console
 * disable more Virtual Reality APIs
 * disable vibrator API
 * when user re-enables URL fixup, still disable it for URLs using 'username:password' syntax
 * enable downloading/using Mozilla SWF blocklists in case some users actually need to re-enable Flash player plugin
 * use master switch browser.selfsupport.enabled to disable Heartbeat, in addition to already empty URL.
 * improve safebrowsing.downloads.enabled description
 * add "Open windows" to default selection in "Clear Private Data" dialog
 * enforce disabling fully automatic password autofill on HTTP sites, even when user re-enables autofill
 * enforce showing an in-content warning for insecure login forms

ignore.list:
 * add browser.safebrowsing.downloads.* fine controls
 * add safebrowsing url prefs
 * explicitely don't set/harden privacy.cpd.passwords/siteSettings and mark it: '(relaxed) ($REASON)' - in this case, reason is better usability - Ref. #231

Thanks to https://github.com/ghacksuserjs/ghacks-user.js/

### CODE REVIEW

**Comment by nodiscc** [comment]
* doc: add reference link for geo.wifi.*:
these preferences are no longer set by default but are still readable and will work correctly:
> The preference is still honored, it is just not in about:config.
> In about:config it should still be possible to create a string preference with that name, and it should work correctly.

 * add WONTFIX items from #208 to ignore.list, up to HARDWARE FINGERPRINTING section;
 * move extra VR API preferencs to ignore.list since VR is globally disabled
 * move New Tab Page/Tiles prefs next to each other

**Comment by nodiscc** [comment]
* 341f024 ignore network.http.redirection-limit, disable in-content SVG rendering item 2671 of #208 states this pref should not be altered for convenience purposes: disable SVG spport anyway and add a clear notice about breaking functionality this setting should be removed in "relaxed" variants; ref #231
* 4ee5f90 add tab warnings to ignore.list
* e419f21 add more ignored settings, add browser.shell.shortcutFavicons remove misplaced pref in ignore.list thanks https://github.com/ghacksuserjs/ghacks-user.js
* b15c546 add more ignored prefs (UI related) thanks https://github.com/ghacksuserjs/ghacks-user.js move DOM Timing API options next to each other
* 372f18e Disable Web Workers TODO: https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#Other_types_of_worker investigate disabling chromeworkers/audioworkers
* a62b05a add more prefs to ignore list (disk cache)
* 80309fc enforce force Firefox update checks, clarify auto update notice, remove deprecated note (can be found through make checkdeprecated)

**Comment by nodiscc** [comment]
@pyllyukko I'm done with this PR. Let me know if anything should be changed. I will submit future changes to a separate Pull Request.

**Comment by nodiscc** [comment]
This PR is confusing and covers several unrelated aspects.
I will close it now and reopen separate Pull Requests for each individual change.
Note that I will not run `make whatdoesitdo` to ease merging/reviewing. @pyllyukko You'll have to run it after merging.

**Comment by pyllyukko** [comment]
> This PR is confusing and covers several unrelated aspects.
> I will close it now and reopen separate Pull Requests for each individual change.

git_horror

Reminds me of this 🤣 

guitar_hero2

**Pull request closed without merging**
