### PR TITLE
More HTTPS

### PR DESCRIPTION
**Pull request by devmapper0**
There is so quiet last time, so I have changed some links to HTTPS. Changed URL where I was redirected. "Are we... something" from Ghostery is down, so I added archive.org link.

### CODE REVIEW

**Comment by pyllyukko** [comment]
Thanks! :)

Indeed it has been quiet recently. But we're still here!

**Comment by Roman-Nopantski** [comment]
line 353: [Test page for Firefox's built-in Phishing Protection](https://itisatrap.org/firefox/its-a-trap.html) ("Web forgeries") = 403 Forbidden
Correct url is https://www.itisatrap.org/firefox/its-a-trap.html
--
line 355: [Test page for Firefox's built-in Malware Protection](https://itisatrap.org/firefox/unwanted.html) (unwanted software) = 403 Forbidden
Correct url is https://www.itisatrap.org/firefox/unwanted.html

**Comment by pyllyukko** [comment]
Hmm. Both URLs work for me without the ```www.``` subdomain. But the <https://itisatrap.org/firefox/its-a-tracker.html> one doesn't.

**Comment by fmarier** [comment]
The URLs should work fine without the `www`. However, it looks like these pages all broke recently.

I filed https://github.com/mozilla/itisatrap/issues/19 to track this.

**Comment by Roman-Nopantski** [comment]
I added these about 4 or five months ago (not sure if you have them all)
   Attack            https://itisatrap.org/firefox/its-an-attack.html
   Blocked           https://itisatrap.org/firefox/blocked.html
   Malware           https://www.itisatrap.org/firefox/unwanted.html
   Phishing          https://www.itisatrap.org/firefox/its-a-trap.html
   Tracking          https://itisatrap.org/firefox/its-a-tracker.html
They weren't ALL HTTPS, so I changed a couple, and then, TBH, my FF is so screwed down, I just tested the URLs in IE. I will fire up a vanilla portable FF and test from there and report back :)

**Comment by Roman-Nopantski** [comment]
@fmarier : I just ran a vanilla FF 50.1 and loaded all five urls with and without the www, so 10 pages in all. All five tests without a www returned a 403, all urls with a www were fine. You might want to log some more tickets

**Pull request merged**
