### PR TITLE
Add a Make target to check settings which have the same values as default Firefox

### PR DESCRIPTION
**Pull request by nodiscc**
Part of https://github.com/pyllyukko/user.js/issues/256

### CODE REVIEW

**Comment by pyllyukko** [comment]
`comm` complains:

```
comm: file 1 is not in sorted order
```

And indeed if I run `diff sourceprefs_sorted.js <(sort sourceprefs_sorted.js)` this seems to be the case.

**Comment by nodiscc** [comment]
Strange, it works for me (Debian stable):

```bash
~/toolbox/MIRRORS/GIT/user.js (make-checkcommonwithupstream=)$ make checkcommonwithupstream
2018-12-14 20:48:31 URL:https://hg.mozilla.org/mozilla-central/raw-file/tip/toolkit/components/telemetry/datareporting-prefs.js [757/757] -> "-" [1]
2018-12-14 20:48:32 URL:https://hg.mozilla.org/mozilla-central/raw-file/tip/toolkit/components/telemetry/healthreport-prefs.js [450/450] -> "-" [1]
2018-12-14 20:48:35 URL:https://hg.mozilla.org/mozilla-central/raw-file/tip/security/manager/ssl/security-prefs.js [7116/7116] -> "-" [1]
2018-12-14 20:48:38 URL:https://hg.mozilla.org/mozilla-central/raw-file/tip/modules/libpref/init/all.js [262384/262384] -> "-" [1]
2018-12-14 20:48:40 URL:https://hg.mozilla.org/mozilla-central/raw-file/tip/testing/profiles/common/user.js [3291/3291] -> "-" [1]
2018-12-14 20:48:42 URL:https://hg.mozilla.org/mozilla-central/raw-file/tip/testing/profiles/reftest/user.js [6330/6330] -> "-" [1]
2018-12-14 20:48:44 URL:https://hg.mozilla.org/mozilla-central/raw-file/tip/js/src/tests/user.js [2048/2048] -> "-" [1]
2018-12-14 20:48:45 URL:https://hg.mozilla.org/mozilla-central/raw-file/tip/browser/app/profile/firefox.js [83891/83891] -> "-" [1]
2018-12-14 20:48:48 URL:https://hg.mozilla.org/mozilla-central/raw-file/tip/devtools/client/preferences/debugger.js [3614/3614] -> "-" [1]
2018-12-14 20:48:49 URL:https://hg.mozilla.org/mozilla-central/raw-file/tip/devtools/client/preferences/devtools-client.js [15136/15136] -> "-" [1]
2018-12-14 20:48:51 URL:https://hg.mozilla.org/mozilla-central/raw-file/tip/browser/branding/unofficial/pref/firefox-branding.js [1614/1614] -> "-" [1]
2018-12-14 20:48:52 URL:https://hg.mozilla.org/mozilla-central/raw-file/tip/browser/branding/official/pref/firefox-branding.js [2117/2117] -> "-" [1]
2018-12-14 20:48:54 URL:https://hg.mozilla.org/mozilla-central/raw-file/tip/browser/branding/nightly/pref/firefox-branding.js [2021/2021] -> "-" [1]
2018-12-14 20:48:57 URL:https://hg.mozilla.org/mozilla-central/raw-file/tip/browser/branding/aurora/pref/firefox-branding.js [1979/1979] -> "-" [1]
2018-12-14 20:48:58 URL:https://hg.mozilla.org/mozilla-central/raw-file/tip/browser/locales/en-US/firefox-l10n.js [221/221] -> "-" [1]
2018-12-14 20:49:00 URL:https://hg.mozilla.org/mozilla-central/raw-file/tip/devtools/client/webide/preferences/webide.js [680/680] -> "-" [1]
2018-12-14 20:49:02 URL:https://hg.mozilla.org/mozilla-central/raw-file/tip/browser/app/profile/channel-prefs.js [258/258] -> "-" [1]
sed 's/^pref(/user_pref(/' sourceprefs.js | sort | sed -E "s/[[:space:]]+/ /g" > sourceprefs_sorted.js
grep "^user_pref" user.js | sort | sed -E "s/[[:space:]]+/ /g" > userjs_sorted.js
comm -1 -2  sourceprefs_sorted.js userjs_sorted.js
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("browser.crashReports.unsubmittedCheck.enabled", false);
user_pref("browser.helperApps.deleteTempFileOnExit", true);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories", false);
user_pref("browser.offline-apps.notify", true);
user_pref("browser.pagethumbnails.capturing_disabled", true);
user_pref("browser.safebrowsing.blockedURIs.enabled", true);
user_pref("browser.safebrowsing.malware.enabled", true);
user_pref("browser.search.geoSpecificDefaults", false);
user_pref("browser.search.region", "US");
user_pref("browser.send_pings", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.urlbar.filter.javascript", true);
user_pref("clipboard.autocopy", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("dom.vr.enabled", false);
user_pref("extensions.blocklist.enabled", true);
user_pref("extensions.getAddons.cache.enabled", false);
user_pref("extensions.update.enabled", true);
user_pref("geo.wifi.uri", "https://location.services.mozilla.com/v1/geolocate?key=%MOZILLA_API_KEY%");
user_pref("keyword.enabled", false);
user_pref("media.getusermedia.audiocapture.enabled", false);
user_pref("media.webspeech.synth.enabled", false);
user_pref("network.captive-portal-service.enabled", false);
user_pref("network.dns.blockDotOnion", true);
user_pref("network.protocol-handler.external.data", false);
user_pref("network.protocol-handler.external.javascript", false);
user_pref("network.stricttransportsecurity.preloadlist", true);
user_pref("places.history.enabled", false);
user_pref("plugins.click_to_play", true);
user_pref("privacy.clearOnShutdown.cache", true);
user_pref("privacy.clearOnShutdown.cookies", true);
user_pref("privacy.clearOnShutdown.downloads", true);
user_pref("privacy.clearOnShutdown.formdata", true);
user_pref("privacy.clearOnShutdown.history", true);
user_pref("privacy.clearOnShutdown.sessions", true);
user_pref("privacy.cpd.cache", true);
user_pref("privacy.cpd.cookies", true);
user_pref("privacy.cpd.downloads", true);
user_pref("privacy.cpd.formdata", true);
user_pref("privacy.cpd.history", true);
user_pref("privacy.cpd.sessions", true);
user_pref("privacy.trackingprotection.pbmode.enabled", true);
user_pref("privacy.userContext.enabled", true);
user_pref("security.dialog_enable_delay", 1000);
user_pref("security.fileuri.strict_origin_policy", true);
user_pref("security.insecure_field_warning.contextual.enabled", true);
user_pref("security.insecure_password.ui.enabled", true);
user_pref("security.mixed_content.block_active_content", true);
user_pref("security.OCSP.enabled", 1);
user_pref("security.sri.enable", true);
user_pref("security.ssl3.ecdhe_ecdsa_chacha20_poly1305_sha256", true);
user_pref("security.ssl3.ecdhe_rsa_chacha20_poly1305_sha256", true);
user_pref("security.ssl.enable_ocsp_must_staple", true);
user_pref("security.ssl.enable_ocsp_stapling", true);
user_pref("security.ssl.errorReporting.automatic", false);
user_pref("security.tls.version.max", 4);
user_pref("security.tls.version.min", 1);
user_pref("signon.autofillForms.http", false);
user_pref("toolkit.telemetry.enabled", false);
```

**Comment by nodiscc** [comment]
May be something to do with your custom `Make` configuration (parallelism?)

**Comment by nodiscc** [comment]
Rebased, added some makefile cleanup. Does `make upstream-duplicates` work for you?
Otherwise I can remove the new target and just keep the cleanup commits. But it works for me.

**Comment by nodiscc** [comment]
This PR has been open for more than 2 years. Let's fix and merge it, or close it ;)

**Comment by pyllyukko** [comment]
One of the URLs returns 404:

```
https://hg.mozilla.org/mozilla-central/raw-file/tip/devtools/client/webide/preferences/webide.js:
2021-01-14 23:15:45 ERROR 404: Not Found.
```
And I still get this:

```
comm: input is not in sorted order
make: *** [Makefile:95: upstream-duplicates] Error 1
```

**Comment by pyllyukko** [comment]
ddbdb08210dd73eb21272c5c45658f6f54e28ccc

**Comment by nodiscc** [comment]
https://github.com/pyllyukko/user.js/commit/9d6e237983453606951016075899c537f1bc7c35 Thanks for fixing it! I don't know exactly why we were getting different results :thinking: 

> One of the URLs returns 404:

-> https://github.com/pyllyukko/user.js/pull/506

**Pull request merged**
