### PR TITLE
disk cache: add 2 commented out prefs for reference

### PR DESCRIPTION
**Pull request by nodiscc**
Fixes item 1001 in #208

### CODE REVIEW

**Comment by pyllyukko** [comment]
I think this needs some additional researching and links in the user.js. Sounds like something that ```browser.cache.disk.enable``` already handles.

**Comment by nodiscc** [comment]
Added documentation

**Comment by pyllyukko** [comment]
Still... do we need these at all? Smart or dumb, the disk cache isn't in use and that can be verified from ```about:cache```:

```
Number of entries: 	0
Maximum storage size: 	32768 KiB
Storage in use: 	0 KiB
Storage disk location: 	none, only stored in memory 
```
Of course there's the "When disk cache is enabled" note, but is it unnecessary clutter?

**Comment by nodiscc** [comment]
You are right. Closing, feel free to mark #208 item 1001 as fixed (#214)

**Comment by pyllyukko** [comment]
Done.

**Pull request closed without merging**
