### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gaborgulyas**
I added two fingerprint sites:
- Browser Extension and Login-Leak Experiment: https://extensions.inrialpes.fr
- Cross-browser fingerprinting test 2.0: https://fingerprint.pet-portal.eu

### CODE REVIEW

**Comment by pyllyukko** [comment]
The Cross-browser fingerprinting test 2.0 doesn't seem to work for me. It doesn't get to the end. Does it work for others?

**Comment by gaborgulyas** [comment]
Yeah, 48 results were dropped in the DB in the last 24h. It also works for me.

**Comment by nodiscc** [comment]
https://fingerprint.pet-portal.eu/ works for me

**Comment by pyllyukko** [comment]
Still doesn't work for me. Sorry, but I'm not merging this.

**Pull request closed without merging**
